#!/usr/bin/env lua
print ("This script can be executed standalone!")

-- Reading with io
io.write('Holle there, what is your name? ')
local name = io.read()
io.write('Nice to meet you, ', name, '!\n')
